### ISSUE TITLE
Trained on BlendedMVS

### ISSUE THREAD

**Issue by JianfeiJ** [bdwsq1996/Effi-MVS#10]
Hi, when I train Effi-MVS on BlendedMVS, the following happens, how can I fix it? 
![图片1](https://github.com/bdwsq1996/Effi-MVS/assets/98368257/5542d421-ff0f-46c0-9892-a92a19cca6ff)

**Comment by bdwsq1996** [comment]
You can try using the “homo_warping2” function to warp the feature maps in class DepthNet and class GetCost.

**Comment by JianfeiJ** [comment]
I have solved the problem, thank you for your response.
