### ISSUE TITLE
BlendMVS dataset download link is not available now

### ISSUE THREAD

**Issue by ericufatass** [bdwsq1996/Effi-MVS#11]
Hello, thanks for your nice work! I found that the BlendMVS dataset download link in the readme file is no longer available. When I went to the corresponding official data set download ,I don’t know what version of the dataset to download. Can you provide the corresponding download link again? Or tell me which version to download?

**Comment by bdwsq1996** [comment]
You can download the low-resolution version of the BlendMVS dataset in https://github.com/YoYo000/BlendedMVS.
The URL is https://1drv.ms/u/s!Ag8Dbz2Aqc81gVDu7FHfbPZwqhIy?e=BHY07t

**Comment by ericufatass** [comment]
Thanks a lot  : )
