### ISSUE TITLE
Question about dataloader

### ISSUE THREAD

**Issue by MiaoJieF** [bdwsq1996/Effi-MVS#4]
Shouldn't this line read depth_min and depth_max? Why depth_min and depth_interval?
https://github.com/bdwsq1996/Effi-MVS/blob/1a23a34f3aeada6b58e85107ad43850cd2c676c8/datasets/dtu_yao_1to8_inverse.py#L149

**Comment by bdwsq1996** [comment]
> Shouldn't this line read depth_min and depth_max? Why depth_min and depth_interval?
> 
> https://github.com/bdwsq1996/Effi-MVS/blob/1a23a34f3aeada6b58e85107ad43850cd2c676c8/datasets/dtu_yao_1to8_inverse.py#L149

![image](https://user-images.githubusercontent.com/48882328/202894605-1fb54536-0fb4-421a-8ac5-9b139a8f3dbb.png)

This is the 00000000_cam.txt in DTU training datasets. In the last line, 425 is the depth_min, 2.5 is a default depth_interval.

**Comment by MiaoJieF** [comment]
> 

Thank you for your reply. This is probably due to the different camera parameters in the data set I downloaded. Could you please send me a copy of the camera parameters you use? My email is M202272557@hust.edu.cn.
