### ISSUE TITLE
Question about camera intrinsics

### ISSUE THREAD

**Issue by MiaoJieF** [bdwsq1996/Effi-MVS#5]
Shouldn't stage1 correspond to 1/8 resolution? Why not multiply by 0.125 instead of 0.5?
https://github.com/bdwsq1996/Effi-MVS/blob/1a23a34f3aeada6b58e85107ad43850cd2c676c8/datasets/dtu_yao_1to8_inverse.py#L176

**Comment by bdwsq1996** [comment]
The DTU dataset contains two types of camera parameters, one corresponding to the full resolution image(1600 * 1200) and the other corresponding to the (160 * 128) size image. We read the camera parameters that corresponding to (160 * 128) size images in our dtu_yao_1to8_inverse.py.  Since the size of the training image is 640 * 512, so we use:
stage1_pjmats[:, 1, :2, :] = proj_matrices[:, 1, :2, :] * 0.5 

Many MVS works followed the codes of MVSNet and CasMVSNet in data preprocessing, so as our work. Our work rarely changes the data preprocessing code of CasMVSNet. Indeed, this part of the code is easily misunderstood. But most people are reluctant to change this part of code, because it does not affect the operation of the program.

**Comment by MiaoJieF** [comment]
> The DTU dataset contains two types of camera parameters, one corresponding to the full resolution image(1600 * 1200) and the other corresponding to the (160 * 128) size image. We read the camera parameters that corresponding to (160 * 128) size images in our dtu_yao_1to8_inverse.py. Since the size of the training image is 640 * 512, so we use: stage1_pjmats[:, 1, :2, :] = proj_matrices[:, 1, :2, :] * 0.5
> 
> Many MVS works followed the codes of MVSNet and CasMVSNet in data preprocessing, so as our work. Our work rarely changes the data preprocessing code of CasMVSNet. Indeed, this part of the code is easily misunderstood. But most people are reluctant to change this part of code, because it does not affect the operation of the program.

Thank you for your reply. I read the CasMVSNet code and found this to be the case. I get this question because the IterMVS code multiplies the 1/8 resolution intrinsics by 0.125.

However, I compared the parameter file of the IterMVS dataset with the parameter file of Effi-MVS, and everything was the same except the minimum and maximum depths. I'm new to this field and I don't really understand it. May I ask why?

**Comment by bdwsq1996** [comment]
The depth range of DTU dataset is 425-935. Maybe different works have different data processing methods, but these works all ensure that the depth range is 425-935(except CER-MVS, the data processing step of this work is quite special). For example, in our work, min-depth=425, max-depth=425+384*(1.06 / (384.0/192.0) *2.5) = 933.8.

**Comment by bdwsq1996** [comment]
> > The DTU dataset contains two types of camera parameters, one corresponding to the full resolution image(1600 * 1200) and the other corresponding to the (160 * 128) size image. We read the camera parameters that corresponding to (160 * 128) size images in our dtu_yao_1to8_inverse.py. Since the size of the training image is 640 * 512, so we use: stage1_pjmats[:, 1, :2, :] = proj_matrices[:, 1, :2, :] * 0.5
> > Many MVS works followed the codes of MVSNet and CasMVSNet in data preprocessing, so as our work. Our work rarely changes the data preprocessing code of CasMVSNet. Indeed, this part of the code is easily misunderstood. But most people are reluctant to change this part of code, because it does not affect the operation of the program.
> 
> Thank you for your reply. I read the CasMVSNet code and found this to be the case. I get this question because the IterMVS code multiplies the 1/8 resolution intrinsics by 0.125.
> 
> However, I compared the parameter file of the IterMVS dataset with the parameter file of Effi-MVS, and everything was the same except the minimum and maximum depths. I'm new to this field and I don't really understand it. May I ask why?

The depth range of DTU dataset is 425-935. Maybe different works have different data processing methods, but these works all ensure that the depth range is 425-935(except CER-MVS, the data processing step of this work is quite special). For example, in our work, min-depth=425, max-depth=425+384*(1.06 / (384.0/192.0) *2.5) = 933.8.

**Comment by MiaoJieF** [comment]
> > > The DTU dataset contains two types of camera parameters, one corresponding to the full resolution image(1600 * 1200) and the other corresponding to the (160 * 128) size image. We read the camera parameters that corresponding to (160 * 128) size images in our dtu_yao_1to8_inverse.py. Since the size of the training image is 640 * 512, so we use: stage1_pjmats[:, 1, :2, :] = proj_matrices[:, 1, :2, :] * 0.5
> > > Many MVS works followed the codes of MVSNet and CasMVSNet in data preprocessing, so as our work. Our work rarely changes the data preprocessing code of CasMVSNet. Indeed, this part of the code is easily misunderstood. But most people are reluctant to change this part of code, because it does not affect the operation of the program.
> > 
> > 
> > Thank you for your reply. I read the CasMVSNet code and found this to be the case. I get this question because the IterMVS code multiplies the 1/8 resolution intrinsics by 0.125.
> > However, I compared the parameter file of the IterMVS dataset with the parameter file of Effi-MVS, and everything was the same except the minimum and maximum depths. I'm new to this field and I don't really understand it. May I ask why?
> 
> The depth range of DTU dataset is 425-935. Maybe different works have different data processing methods, but these works all ensure that the depth range is 425-935(except CER-MVS, the data processing step of this work is quite special). For example, in our work, min-depth=425, max-depth=425+384*(1.06 / (384.0/192.0) *2.5) = 933.8.

Yes. The question I want to ask is camera intrinsics. IterMVS and Effi-MVS use the same camera parameters. Why is IterMVS multiplied by 0.125 at 1/8 resolution and Effi-MVS multiplied by 0.5?

**Comment by bdwsq1996** [comment]
> 

I just read the code of IterMVS. IterMVS processed the camera parameters.
![image](https://user-images.githubusercontent.com/48882328/203022320-97553dbd-25f2-4b3e-969e-6e42997bfa6f.png)
This is the readme in IterMVS.

**Comment by MiaoJieF** [comment]
> > 
> 
> I just read the code of IterMVS. IterMVS processed the camera parameters. ![image](https://user-images.githubusercontent.com/48882328/203022320-97553dbd-25f2-4b3e-969e-6e42997bfa6f.png) This is the readme in IterMVS.

Yes. IterMVS reprocesses the data. But I downloaded the processed camera parameters and found that IterMVS only modified the maximum and minimum depth, using the same camera parameters as Effi-MVS. Maybe you can compare them if you have time.

**Comment by bdwsq1996** [comment]
> > > 
> > 
> > 
> > I just read the code of IterMVS. IterMVS processed the camera parameters. ![image](https://user-images.githubusercontent.com/48882328/203022320-97553dbd-25f2-4b3e-969e-6e42997bfa6f.png) This is the readme in IterMVS.
> 
> Yes. IterMVS reprocesses the data. But I downloaded the processed camera parameters and found that IterMVS only modified the maximum and minimum depth, using the same camera parameters as Effi-MVS. Maybe you can compare them if you have time.

During training:
IterMVS :
![image](https://user-images.githubusercontent.com/48882328/203033856-5732aacf-3f97-4236-99b0-e6b7ec5a413a.png)
During testing
Effi-MVS:
![image](https://user-images.githubusercontent.com/48882328/203034229-d5da37ce-05e6-4ed7-9bc5-303f6e945974.png)

**Comment by MiaoJieF** [comment]
Thanks! You save my day!
