### ISSUE TITLE
The indicators are much worse

### ISSUE THREAD

**Issue by LiPan123456789** [bdwsq1996/Effi-MVS#6]
Hello, the result indicators I ran were 0.3232, 0.4638, 0.3935, while the results in the paper were 0.321, 0.313, 0.317. Why is my completeness indicator Comp so much worse, thanks!

**Comment by bdwsq1996** [comment]
> Hello, the result indicators I ran were 0.3232, 0.4638, 0.3935, while the results in the paper were 0.321, 0.313, 0.317. Why is my completeness indicator Comp so much worse, thanks!

Did you use the DTU.ckpt for testing?  If you use the DTU.ckpt, can you tell me the file size of the output mvsnet001_l3.ply.

**Comment by LiPan123456789** [comment]
Hi, after using the DTU.ckpt test, the metrics in the paper are met (001.ply has a size of 537415kb). I don't understand why there is such a big gap in the test of my own trained model, because the parameters are set according to the training details in the paper, can you help me to troubleshoot?

**Comment by bdwsq1996** [comment]
> Hi, after using the DTU.ckpt test, the metrics in the paper are met (001.ply has a size of 537415kb). I don't understand why there is such a big gap in the test of my own trained model, because the parameters are set according to the training details in the paper, can you help me to troubleshoot?

We can further communicate through WeChat: bdwsq1996
