### ISSUE TITLE
List index out of range when reading Tanks and Templates

### ISSUE THREAD

**Issue by StereoResearcher** [bdwsq1996/Effi-MVS#8]
Dear professor:
I downloaded the T&T dataset that your link points to and am having a problem evaluating it.
```
File". /datasets/ tank.py".
line 80, in read_cam_flle
depth max = float(Lines[11].split()[3])
IndexError: List index out of range
```
Do you know what is going on?
I have made the following changes before proceeding with this step. The original code of your test.py is
```
ref_intrinsics, ref_extrinsics, ref_depth_max, ref_depth_min = read_camera_parameters(
            os.path.join(scan_folder, 'cams/{:0>8}_cam.txt'.format(ref_view)))

```
I changed the 'cams' to 'cams_1'. And
`proj_mat_filename = os.path.join(self.datapath, split, scan, f'cams/{vid:08d}_cam.txt')`
I also changed 'cams' to 'cams_1' in tank.py.

**Comment by bdwsq1996** [comment]
The tank dataset has been updated, with two common versions. These two versions only have differences in depth range. The last line in the camera parameter file contains the depth range. In the old version of the dataset, the last line in the parameter file contained 4 values. In the new version of the dataset, the last line in the parameter file contains two values, namely the minimum and maximum depth values. The data processing code for this work corresponds to the old version dataset. I will update the code recently

**Comment by StereoResearcher** [comment]
Thank you so much! I also find the solution recently. I have already solve this problem. I can provide the code if you need it.



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/21/2023 10:17 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [bdwsq1996/Effi-MVS] List index out of range when reading Tanks and Templates (Issue #8) |

The tank dataset has been updated, with two common versions. These two versions only have differences in depth range. The last line in the camera parameter file contains the depth range. In the old version of the dataset, the last line in the parameter file contained 4 values. In the new version of the dataset, the last line in the parameter file contains two values, namely the minimum and maximum depth values. The data processing code for this work corresponds to the old version dataset. I will update the code recently
